image: node:10-alpine

before_script:
  - npm install -g vsce
  - npm install -g typescript

stages:
  - prepare
  - build
#  - package

prepare:
  stage: prepare
  script:
    - npm install
  cache:
    paths:
      - node_modules/

transpile:
  stage: build
  script:
    - tsc -p ./
  cache:
    paths:
      - node_modules/
    policy: pull
#package:
#  stage: package
#  cache:
#    paths:
#      - node_modules/
#    policy: pull
#  script:
#    - vsce package
#  artifacts:
#    paths:
#      - code-stats-vscode-*.vsix
