image: node:10-alpine

stages:
  - package
  - publish

package:
  stage: package
  before_script:
    - npm install -g vsce
    - npm install -g typescript
    - npm install -g ovsx
    - npm install
  cache:
    paths:
      - node_modules/
  script:
    - vsce package
  artifacts:
    paths:
      - code-stats-vscode-*.vsix

publish:
  stage: publish
  needs:
    - package
  only:
    - tags
  before_script:
    - npm install -g ovsx
  script:
    - ovsx publish code-stats-vscode-*.vsix -p $OPEN_VSX_TOKEN
